fix 404 page: use createOptimizedPicture for images
hlxsites/eder-group pull request #139
Opened 2023-02-02 08:25 UTC by mtilburgadobe

use createOptimizedPicture for images to add fallbacks for jpeg and create picture tag

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #138 

Test URLs:
- Before: https://main--eder-group--hlxsites.hlx.page/404.html
- After: https://issue-27--eder-group--hlxsites.hlx.page/404.html

2023-02-02 10:07 UTC, mhaack requested changes

2023-02-02 10:07 UTC, mhaack commented on 404.html
> +                import { createOptimizedPicture } from './scripts/lib-franklin.js';
Import is done twice. Lets move the import to an `<script>` tag in `<head>`

2023-02-02 14:43 UTC, mtilburgadobe commented on 404.html
> +                import { createOptimizedPicture } from './scripts/lib-franklin.js';
Hi @mhaack - been trying several different possibilities here, problem is when I import it in <head> it's not available in <body>.  The import has to be in a script of type module, and some googling shows that references are not available cross modules in an html file...

Any ideas of how to achieve this?

2023-02-02 14:59 UTC, alexcarol commented on 404.html
> +                import { createOptimizedPicture } from './scripts/lib-franklin.js';
Why not include a js file via script tag instead?

2023-02-02 15:10 UTC, mtilburgadobe commented on 404.html
> +                import { createOptimizedPicture } from './scripts/lib-franklin.js';
@alexcarol - I tried this as well.  The function is defined in lib-franklin.js, but including this file also does not work(and probably not any better than importing just the function)

2023-02-02 15:16 UTC, mtilburgadobe commented on 404.html
> +                import { createOptimizedPicture } from './scripts/lib-franklin.js';
I have an idea, I will move it all into the same script at the end of <body>

2023-02-02 15:19 UTC, mtilburgadobe commented on 404.html
> +                import { createOptimizedPicture } from './scripts/lib-franklin.js';
ah yes, that worked

2023-02-02 15:24 UTC, mtilburgadobe commented on 404.html
> +                import { createOptimizedPicture } from './scripts/lib-franklin.js';
@mhaack / @alexcarol - please take another look

2023-02-02 15:46 UTC, mtilburgadobe commented
found another issue, seems this breaks if there is a 404 page not at root, for example:

https://issue-27--eder-group--hlxsites.hlx.page/newstermine/pressemeldungen/doesnotexist

2023-02-03 11:06 UTC, mhaack approved these changes

2023-02-03 11:07 UTC, merged