fix styles on sidebar for non-contacts
hlxsites/eder-group pull request #146
Opened 2023-02-03 14:12 UTC by mtilburgadobe

Fix for Sidebar button space and heading font side are wrong

Fix #130 

Test URLs:
- Before: https://main--eder-group--hlxsites.hlx.page/karriere/ausbildungsangebot
- After: https://issue-130--eder-group--hlxsites.hlx.page/karriere/ausbildungsangebot

2023-02-03 15:55 UTC, mhaack commented
We also have #135 with similar button style issues. I suggest we first remove any margins from the `a.button` in style.css (see https://github.com/hlxsites/eder-group/blob/main/styles/styles.css#L205). This might already fix this ticket and #135. Then we can read button margin at block level where needed. WDYT?

2023-02-05 13:17 UTC, mhaack requested changes

2023-02-05 13:17 UTC, mhaack commented on styles/styles.css
> +  margin-bottom: unset;
Instead of unsetting the margins we should remove them from `a` in `styles.css` globally and then set them on block level where needed.

2023-02-05 13:17 UTC, mhaack commented on styles/styles.css
> +  margin: unset;
Instead of unsetting the margins and paddings we should remove them from a in styles.css globally and then set them on block level where needed.

2023-02-07 12:34 UTC, mtilburgadobe commented on styles/styles.css
> +  margin: unset;
Fixed, I checked several other pages as well, I guess we are good

2023-02-07 15:18 UTC, mhaack commented on styles/styles.css
> +main.sidebar .section.sidebar .default-content-wrapper h2 {
Headline font-size is different then original, looks too big IMHO.

2023-02-08 06:06 UTC, mtilburgadobe commented on styles/styles.css
> +main.sidebar .section.sidebar .default-content-wrapper h2 {
@mhaack -> Font size is 22px in eder.com and in this branch, do you have a screenshot of the difference?

2023-02-08 08:05 UTC, mhaack commented on styles/styles.css
> +main.sidebar .section.sidebar .default-content-wrapper h2 {
Oh sorry, I tested the main branch. Looks good on your branch.

2023-02-08 08:05 UTC, mhaack approved these changes

2023-02-08 09:21 UTC, merged