Fix button alignment in card teasers
hlxsites/eder-group pull request #149
Opened 2023-02-05 12:42 UTC by mtilburgadobe

Fix button alignment in card teasers

Fix #135 

Test URLs:
- Before: https://main--eder-group--hlxsites.hlx.page/
- After: https://issue-135--eder-group--hlxsites.hlx.page/

2023-02-05 13:16 UTC, mhaack requested changes

2023-02-05 13:16 UTC, mhaack commented on blocks/cards/cards.css
> +    margin-top: unset;
Instead of unsetting the margins we should remove them from `a` in `styles.css` globally and then set them on block level where needed. This will also help for PR #146 as there we unset them as well.

2023-02-06 16:14 UTC, mtilburgadobe commented on blocks/cards/cards.css
> +    margin-top: unset;
@mhaack - I ended up just removing it from styles.css... I actually added this as the very first issue for the default styles, but I went through all the different sections of the site and don't see it making a difference without it there.

2023-02-06 17:11 UTC, mhaack approved these changes

2023-02-07 08:10 UTC, merged