Sidebar leftovers
hlxsites/eder-group pull request #59
Opened 2023-01-10 13:36 UTC by basecode

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #6. Are there any other leftovers?

Test URLs:
- Before: https://main--eder-group--hlxsites.hlx.page/unternehmen/ueber-uns
- After: https://6-sidebar-leftovers--eder-group--hlxsites.hlx.page/unternehmen/ueber-uns

2023-01-11 08:00 UTC, mhaack commented
Can we also set the left/right margins and the default light grey background with this PR or would that be another one?

2023-01-11 08:26 UTC, basecode commented
> Can we also set the left/right margins and the default light grey background with this PR or would that be another one?

This PR.

2023-01-13 16:57 UTC, basecode commented on styles/styles.css
> +  word-wrap: break-word;
This was needed due to a very loooong link in the content which prevented nice mobile layout.

2023-01-13 17:03 UTC, mhaack commented on styles/styles.css
> +  word-wrap: break-word;
This link`https://6-sidebar-leftovers--eder-group--hlxsites.hlx.page/newstermine/pressemeldungen/detail/bayerns-best-50-familienunternehmen-eder-gmbh-ist-preistraeger-2020/`? This should actually be combined with the image (different PR). Maybe mark this as //TODO or so that we remove later once the image link is fixed.

2023-01-13 17:05 UTC, mhaack requested changes

2023-01-13 17:05 UTC, mhaack commented on styles/styles.css
> +  main {
This breaks the `wide` layout see https://6-sidebar-leftovers--eder-group--hlxsites.hlx.page/, make sure this does not apply if `wide` is set.

2023-01-13 17:25 UTC, basecode commented on styles/styles.css
> +  main {
👍 I thought I checked this and now realise, when I click around it redirects me to eder-gmbh.de :/

2023-01-13 17:35 UTC, mhaack commented on styles/styles.css
> +  main {
Ha yes reminds me we need to fix some links in the content docs

2023-01-16 11:06 UTC, basecode commented
> Still has some impact on the main homepage layout?
> 
> This was center before and should be center: ![Screenshot 2023-01-16 at 10 02 25](https://user-images.githubusercontent.com/2643450/212638806-1d77ba2b-bf73-4329-be94-0cc60a3b155a.png)

@mhaack thanks! Was able to reproduce on large screensize and fixed the regression.

2023-01-16 15:03 UTC, mhaack approved these changes

2023-01-16 15:54 UTC, merged