feat: press release / latest news block for homepage
hlxsites/eder-group pull request #63
Opened 2023-01-11 12:46 UTC by mhaack

Fix #17 

Test URLs:
- Before: https://main--eder-group--hlxsites.hlx.page/
- After: https://latest-news--eder-group--hlxsites.hlx.page/

2023-01-13 12:19 UTC, steinkopffp requested changes

2023-01-13 12:19 UTC, steinkopffp commented on blocks/latest-news/latest-news.css
> +.latest-news {
This style breaks the mobile display. I would suggest to place this inside a breakpoint

2023-01-13 13:05 UTC, mhaack commented on blocks/latest-news/latest-news.css
> +.latest-news {
fixed

2023-01-18 11:12 UTC, steinkopffp requested changes

2023-01-18 11:14 UTC, steinkopffp approved these changes

2023-01-18 13:39 UTC, merged